// src/store/customerSlice.js
import { createSlice } from '@reduxjs/toolkit';

// Define an initial state
const initialState = [];

// Create the slice
const customerSlice = createSlice({
  name: 'customer', // This name will appear in Redux DevTools
  initialState,
  reducers: {
    addCustomer(state, action) {
      state.push(action.payload); // Immer.js handles immutability under the hood
    },
  },
});

// Export the actions generated by createSlice
export const { addCustomer } = customerSlice.actions;

// Export the reducer function, which will be added to the store
export default customerSlice.reducer;
